//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineInvoice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AgentBranch")]
    public partial class AgentBranch
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
         public int AgentBranchID { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Tax { get; set; }
        public string BankAcc { get; set; }
        public string HeaderInvoice { get; set; }
        public string InvoicePrefix { get; set; }
        public string FormNo { get; set; }
        public string Serial { get; set; }
        public string FormNoReturn { get; set; }
        public string SerialReturn { get; set; }
        public string InvoiceStartNumber { get; set; }
        public string InvoiceEndNumber { get; set; }
        public string InvoiceReturnStart { get; set; }
        public string InvoiceReturnEnd { get; set; }
        public int AgentID { get; set; }
    }
}
