//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineInvoice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Agent")]
    public partial class Agent
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int AgentID { get; set; }
        public string AgentName { get; set; }
        public string AgentCompanyName { get; set; }
        public string AgentCompanyAddress { get; set; }
        public string AgentTaxCode { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public string SigninSabre { get; set; }
        public string PasscodeSabre { get; set; }
        public string SuffixSabre { get; set; }
        public string HardcopyPrinterAddress { get; set; }
        public string TicketPrinterAddress { get; set; }
        public string TicketPrintRoutine { get; set; }
        public string StationNumber { get; set; }
        public string AgentLogo { get; set; }
        public int ParentID { get; set; }
    }
}
