//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineInvoice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Invoice")]
    public partial class Invoice
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public DateTime InvoiceDate { get; set; }
        public double? Total { get; set; }
        public int? TotalFee { get; set; }
        public int AgentID { get; set; }
        public int AgentBranchID { get; set; }
        public string UserCreate { get; set; }
        public DateTime DateCreate { get; set; }    
        public int? InvoiceType { get; set; }
        public int? PaymentType { get; set; }
        public string Note { get; set; }
        public int? CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerTax { get; set; }
        public int? InvoiceStatus { get; set; }
        public int? TotalAgentFee { get; set; }
        public string EInvoiceNumber { get; set; }   
        public string ENumber { get; set; }
        public string Pattern { get; set; }
        public string Email { get; set; }                       
        [NotMapped]
        public List<InvoiceDetail> InvoiceDetails { get; set; }
        public List<InvoiceDetail> DetailList { get; set; }
        [NotMapped]
        public int ActionMode { get; set; }
        [NotMapped]
        public string InvoiceDetailJson { get; set; }
        [NotMapped]
        public string BranchName { get; set; }
        [NotMapped]
        public string AgentCompanyName { get; set; }
        [NotMapped]
        public string BranchAddress { get; set; }
        [NotMapped]
        public string BranchTax { get; set; }
        [NotMapped]
        public string FormNo { get; set; }
        [NotMapped]
        public string Serial { get; set; }
        [NotMapped]
        public int PrintCopy { get; set; }
        [NotMapped]
        public string PrintCopyString { get; set; }
        [NotMapped]
        public string Seller { get; set; }
        [NotMapped]
        public string DetailListLabel { get; set; }
        [NotMapped]
        public string Buyer { get; set; }
        [NotMapped]
        public string AgentTel { set; get; }
        [NotMapped]
        public string AgentEmail { set; get; }
    }
}
